" Check if there is need to install vimplug
let need_to_install_plugins = 0

if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    "autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    let need_to_install_plugins = 1
endif

call plug#begin('~/.vim/plugged')
    Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
    Plug 'bling/vim-airline' " Add status line to vim
    Plug 'jiangmiao/auto-pairs'  " Auto close for () and {} and so on.
    Plug 'tpope/vim-surround' " Easily add \" or change it
    Plug 'ervandew/supertab'  " Autocomplete based on previous words
    Plug 'fisadev/vim-isort'  "Sort import modules in python program with execute :Isort
    Plug 'townk/vim-autoclose'  " close \", (, [ and ..
    Plug 'nvie/vim-flake8'  " Add flake8 syntax checker
    Plug 'tpope/vim-repeat'
    Plug 'mattn/emmet-vim'  " Autocomplete for HTML TAG
    Plug 'sjl/badwolf'  " Color-Schema
    Plug 'psf/black'  " Add black integration
call plug#end()

if need_to_install_plugins == 1
    echo "Installing plugins..."
    silent! PlugInstall
    echo "Done!"
    q
endif

" Customize Plugins
colorscheme badwolf
nnoremap <F9> :NERDTreeToggle<CR>
" NerdTree ShortCut
let mapleader=","  " Set mapleader to ','
" Turn off search highlight by ,<space>
nnoremap <bs> :nohlsearch<CR>
" switch Ctrl-d with shift-tab reverse tab"
inoremap <S-Tab> <C-d>
" Run Black with <leader>b
nnoremap <leader>b :Black<CR>

" Configure vim itself :-D
filetype plugin indent on
set mouse=a  " enable mouse into vim.
set ruler  " Show line number and column number
set number  " Show line number and column number
set cursorline  " Highlight current line.
set encoding=utf-8 " Set character encoding 
set ts=8 sts=4 sw=4 expandtab  " if you work with python it's fantastic.
set hlsearch  " Highlight search matches
set incsearch  " Show matches when searching
set wildmenu  " show menu autocomplete file path :e filename
set showmatch " show matches for () {} [] 
set title  " show the file name at the title
set hidden
set autoindent "Copy the indent from current line
set smartindent
set laststatus=2  "show status bar at the bottom of vim window
set pastetoggle=<F5>  "enable paste toggle mode with F5 key
set ignorecase  " ignore case sensitive

" Move effortlessly between vim tabes with Ctrl+ [h, j, k, l]
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Enable/Disable showing special key with Ctrl + \
    nmap <C-\> :set list!<CR>

" Shortcuts for saving and closing files in vim
" Save current file easily with <leader> + w
nnoremap <leader>w :w!<CR>

" Close current file easily with <leader> + q
nnoremap <leader>q :q!<CR>

" Save a file with root permission
cmap w!! w !sudo tee %

" Enabling Folding Base on indentation and enable and disable by space "
set foldmethod=indent
set foldlevel=99
" fold and unfold with space key
nnoremap <space> za

" Switch to normal mode with pressing <j-k> key instead of <Esc>
inoremap jk <esc>

" Navigate between buffers
map <C-p> :bp<CR>
map <C-n> :bn<CR>
map  <leader>bd :bd!<CR>

" Execute Python code inside vim - James Powell
vnoremap <silent> <leader>e :w ! python3<CR>
nnoremap <silent> <leader>ee :%w ! python3<CR>
